### ISSUE TITLE
Add unmute overlay for autoplayed muted videos

### ISSUE THREAD

**Issue by zcesur** [algora-io/tv#102]
When a video is autoplayed in a muted state, we should overlay a large muted icon on the video. Clicking this icon should unmute the video and remove the overlay.

### Relevant files:

- `assets/js/app.ts`: VideoPlayer hook
- `lib/algora_web/live/hero_component.ex`: renders the video player on homepage
- `lib/algora_web/live/player_component.ex`: renders the video player on other pages

**Comment by Mubashirshariq** [comment]
@zcesur can I get this assigned

**Comment by GauravBurande** [comment]
any feedback on the pull request: #112?

**Comment by shrahul520** [comment]
@zcesur can I get this assigned,then I will start working on this

**Comment by Rushhaabhhh** [comment]
/attempt #102

**Implementation Plan** : 
1. State Tracking : Add a muted state in both HeroComponent and PlayerComponent.
2. Overlay Icon : Show a large muted icon overlay when the video is muted.
3. Click to Unmute : On click, unmute the video and remove the overlay.
4. JavaScript Hook : Handle the unmute action in the VideoPlayer hook and communicate the change to the backend.

**Comment by Rushhaabhhh** [comment]
@zcesur-

I have updated the PR with the requested images. Could you please review it ?

**Comment by lastcanal** [comment]
This is possible to do in Javascript only. 

/attempt #102
