### ISSUE TITLE
enhancement: use Vidstack instead of video.js

### ISSUE THREAD

**Issue by mazz** [algora-io/tv#45]
Vidstack is an up-and-coming JS-based web video player that has recently hit 1.0-RC and already far-outshines video.js as a web player.

https://www.vidstack.io/

**Comment by zcesur** [comment]
Does it support LL-HLS? I'm down to give it a try once #60 lands

**Comment by mazz** [comment]
> Does it support LL-HLS? I'm down to give it a try once #60 lands

Yes, apparently it does. 

https://www.vidstack.io/docs/player/core-concepts/loading#stream-type

it looks like you do

`<MediaPlayer streamType="ll-live">`

or 

`<MediaPlayer streamType="(ll-live:dvr">`

if you want dvr-like features like back-seeking.

**Comment by zcesur** [comment]
Very cool! If this fixes our [iOS playback issues](https://github.com/algora-io/tv/issues/62) out of the box and doesn't introduce new issues, I'd happily switch

I added a $300 bounty on #62 if you wanna give it a shot and see if switching to Vidstack fixes it

**Comment by zcesur** [comment]
Adding a /bounty $100 if anyone wants to tackle this. To make sure the new player behaves like the current, we need to:

- Use the appropriate [provider](https://www.vidstack.io/docs/player/api/providers/hls) based on video type (YouTube, HLS, MP4)
- Autoplay all videos with sound on (except the ones with an `analytics-` prefix). Most browsers won't allow autoplay with sound so we should fallback to muted autoplay. [More info here](https://www.vidstack.io/docs/player/api/autoplay)
- Enable seeking for all video types including livestreams
- Enable picture-in-picture (PiP) mode and fullscreen on rotation
- Start videos at the specified timestamp if provided (via `?t=123` query param)

### Relevant files:

- `assets/vendor/video.js`: replace with a minimized Vidstack JavaScript build w/o framework
- `assets/js/app.ts`: rewrite VideoPlayer hook to use the new player
- `lib/algora_web/live/player_component.ex`: see params passed to the player

**Comment by kaf-lamed-beyt** [comment]
hi @zcesur, I'd love to try this. Please assign me.

**Comment by kaf-lamed-beyt** [comment]
BTW @zcesur, any idea how i can see the changes I'm making to the player? 

I followed the guide [here](https://github.com/algora-io/tv?tab=readme-ov-file#setting-up-the-project). I've been able to do that successfully. Can I get any info on how to see the player in the browser?

**Comment by zcesur** [comment]
Hi @kaf-lamed-beyt, thanks for attempting and consider yourself assigned!
(I'm away from my laptop rn)

To test the player, you can create a video by streaming into your local
server via OBS. You can find your RTMP URL in your user settings

**Comment by kaf-lamed-beyt** [comment]
Ayy! Thank you, @zcesur! 

I've installed OBS on my PC. But, I have no idea why it keeps failing to start up. Lemme make some findings and get back to this.

**Comment by zcesur** [comment]
Awesome, let me know if I can help with anything else!

**Comment by kaf-lamed-beyt** [comment]
Yes. If you're free now... can i DM you on discord?

**Comment by kaf-lamed-beyt** [comment]
Okay... sounds good! 

I've somewhat been able to setup a RTMP server with nginx. I'm trying to see if it is possible to stream to my VLC player.
