### ISSUE TITLE
Deployment on fly.io with master/replica

### ISSUE THREAD

**Issue by mazz** [algora-io/tv#57]
Has anyone gotten this app deployed on fly.io with regional master/replica databases working? 

I'm having trouble getting things configured on fly.io. I'm confused about how it appears you need to create at least two database instances, one master, one replica(and I'm not clear on how to associate the machines along with them).

**Comment by zcesur** [comment]
Hey Michael! Creating a multi-node Postgres cluster is not at all required to deploy Algora TV, you can actually just use a single-node setup. [Fly.io docs](https://fly.io/docs/postgres/connecting/connecting-internal/) walk you through the steps to connect to your database

**Comment by mazz** [comment]
> Hey Michael! Creating a multi-node Postgres cluster is not at all required to deploy Algora TV, you can actually just use a single-node setup. [Fly.io docs](https://fly.io/docs/postgres/connecting/connecting-internal/) walk you through the steps to connect to your database

Yes maybe I’ll try that first, thanks.
