### ISSUE TITLE
Integrate with major streaming services

### ISSUE THREAD

**Issue by zcesur** [algora-io/tv#61]
We need to

1. Integrate [ueberauth](https://github.com/ueberauth/ueberauth) to handle authentication
2. Implement OAuth flows using [ueberauth strategies](https://github.com/ueberauth/ueberauth/wiki/List-of-Strategies) and persist OAuth metadata in [`identity`](https://github.com/algora-io/tv/blob/main/lib/algora/accounts/identity.ex). We wanna support:
   - YouTube (Google)
   - Twitch
   - Twitter
3. Set appropriate API token scopes for each platform. We wanna be able to:
   - Read & manage broadcast/event configuration (title, description, tags etc)
   - Read & manage chat messages
   - Read RTMP URL and stream key
   - Read analytics (concurrent viewers, total views etc, if available)
4. Create multistream destination using user's RTMP URL and stream key once auth flow is completed

**Comment by oliverqx** [comment]
/attempt #61 

would it be possible to get assigned for the next 48 hours?

**Comment by zcesur** [comment]
Hey Oliver! I can assign the issue to you if you'll livestream solving it :) Fair enough?

**Comment by oliverqx** [comment]
that sound good, I'll live stream

**Comment by zcesur** [comment]
Assigned to @oliverqx for the time being

**Comment by onyedikachi-david** [comment]
All the best @oliverqx.

**Comment by harshsbhat** [comment]
All the best @oliverqx. Let us know when and where you livestream. I would love to join

**Comment by onyedikachi-david** [comment]
Hello @harshsbhat, since oliverqx has removed their assignment can i go ahead?

**Comment by zcesur** [comment]
Yeah the issue is open for anyone to attempt. That being said your other PR needs a few changes so I suggest finishing that first @onyedikachi-david. Submitting a review shortly

**Comment by zcesur** [comment]
Good luck @harshsbhat, lmk if you run into any issues setting up local dev or anything else!

**Comment by pmbanugo** [comment]
I'll suggest consider adding LinkedIn. A personal preference is LinkedIn over Twitch for dev/professional content.

**Comment by stdthoth** [comment]
can i attempt this @zcesur ??

**Comment by zcesur** [comment]
Splitting this up separate issues (starting with #104)
