### ISSUE TITLE
Fix LL-HLS playback on iOS

### ISSUE THREAD

**Issue by zcesur** [algora-io/tv#62]
We currently use HLS to deliver livestreams and VODs to users, which works fine on most devices and browsers. We also implemented LL-HLS delivery (#60), which mostly works except on iOS devices. Since LL-HLS is an Apple protocol, it's likely that either the video player we're using (video.js) or the custom controller we wrote (which delivers manifests, segments, and partials) is incompatible in some way.

## Steps to Reproduce

1. Check out the `ll-hls` branch
2. Set up and run the development server
3. Paste your RTMP URL into OBS and start streaming
4. Navigate to your stream on an iOS device

## Useful Links

- [videojs/video.js: Video.js - open source HTML5 video player](https://github.com/videojs/video.js)
- [videojs/http-streaming: HLS, DASH, and future HTTP streaming protocols library for video.js](https://github.com/videojs/http-streaming)
- [Enabling Low-Latency HTTP Live Streaming (HLS) | Apple Developer Documentation](https://developer.apple.com/documentation/http-live-streaming/enabling-low-latency-http-live-streaming-hls)

**Comment by amochuko** [comment]
/attempt #62 

I will follow the outlined referenced resource link to get better understanding of video.js config with streamType and analyzed that for the LL-HLS playback on iOS for a resolve.

If that doesn't fan out, I would review your in-house custom controller compatibility before eventually resulting to a possible test with vidstack (as noted in this issue: https://github.com/algora-io/tv/issues/45)

**Comment by zcesur** [comment]
Closing this for now, but do let me know if you made any progress @sivaprasad2000
