### ISSUE TITLE
Implement tagging system for videos and channels

### ISSUE THREAD

**Issue by zcesur** [algora-io/tv#70]
Both `users` and `videos` should have a `tags` field that's a list of strings.

Videos should be initialized with the current tags of the user. Users should be able to set their current tags from user settings.

Let's use regular text input and a list of badges that appear beneath it. Hitting enter inside the input should add the tag to the list. Clicking on a badge should remove it from the list.

**Comment by govindup63** [comment]
/attempt #70 
can you assign this issue to me?

**Comment by Kishan-Kulkarni** [comment]
Is this issue still open, if it is I'd like to work on it as I am pretty interested
