### ISSUE TITLE
Revamp homepage layout and UI components

### ISSUE THREAD

**Issue by zcesur** [algora-io/tv#72]
| Current homepage     | New homepage        |
| -------------------- | ------------------- |
| <img src="https://github.com/user-attachments/assets/3d694268-b0d2-4f22-ac44-0efb9841b786" width="600" /> | <img src="https://github.com/user-attachments/assets/41f2028f-3bb4-4c24-ac72-8f2a3fdb21e8" width="600" /> |

We already have all of the individual components. We need to restyle a bunch of stuff and move some things around.

## In scope:

- Top bar
- Restyled sidebar
- Everything else besides active streamers moved to the user menu at top right
- Sidebar takes up its own space (as opposed to being overlayed on top of the page)
- Sidebar is open by default except when there is a chatbox open
- Full width hero video
  - Currently we show a hero video only if there is an active livestream
  - Going forward we should always show a hero video
  - If there is no active livestream, we should fallback to the latest VOD
- Full responsiveness
- Black background everywhere (perhaps with a slight gradient)

## Out of scope:

- Offline streamers in sidebar
- Viewer counts in sidebar
- "See all livestreams" button
- Stream tags

**Comment by Bhavyajain21** [comment]
/attempt #72

Can I be assigned @zcesur

**Comment by Bhavyajain21** [comment]
Can I be assigned? @zcesur

**Comment by zcesur** [comment]
Hey @Bhavyajain21 thanks for tackling this! Happy to assign once there's meaningful progress

**Comment by Brihadeeshrk** [comment]
/attempt #72 My plan is to first go through the current UI, understand what's going on and then make the proposed changes as per the new design

**Comment by zcesur** [comment]
Thanks for attempting everyone! I just added a database seed script that should make it easier to get started with this issue. It adds 1 live user, 5 VODs and 1 live stream. You can run the script as:

```sh
git pull origin main
env $(cat .env | xargs -L 1) mix run priv/repo/seeds.exs
```

Let me know any time if I can help with anything, also available on [Discord](https://algora.io/discord) via #contributing channel or DMs

**Comment by urbit-pilled** [comment]
this is more complex than I thought it would be, I opened a draft PR and I'll come back to this later tomorrow.

**Comment by zcesur** [comment]
Let me know if there's anything in particular that's giving you trouble, I'd love to help

I need this for a demo next Thursday so I'll have to take over and close the bounty unless there's good progress by the end of the weekend

**Comment by urbit-pilled** [comment]
Sorry @zcesur I was busy over the weekend. Thanks for taking over, I see that you've already made progress on this with the latest commits.

**Comment by zcesur** [comment]
No worries @urbit-pilled. Just in time for the demo :)
