### ISSUE TITLE
Capture multiple thumbnails per stream and allow streamer to select one

### ISSUE THREAD

**Issue by zcesur** [algora-io/tv#81]
We already capture a thumbnail for each livestream. Let's update `Algora.Pipeline.Storage` so we capture multiple (up to 6) thumbnails

I think we should use exponential backoff (e.g. on minute 0, 1, 2, 4, 8, 16) so that we get a few options from the get-go and a few more later for variety. `Algora.Pipeline.Storage` module is segment-based so the math should be done by counting the segments (1 segment = 2 seconds)

Let's also add a simple modal on `AlgoraWeb.VideoLive` that allows the streamer to select one of the 6 generated thumbnails

**Comment by samrat** [comment]
/attempt #81

👋 I'd like to take a shot at implementing this. 

> (e.g. on minute 0, 1, 2, 4, 8, 16) so that we get a few options from the get-go and a few more later for variety.

@zcesur Just to clarify I understood this correctly: we'd still capture 6 thumbnails total, and not replace the earlier thumbnails, right?

**Comment by zcesur** [comment]
Hey great to see you here @samrat!

And yeah, exactly

**Comment by samrat** [comment]
Hey, I've not been able to work on this because of some other priorities. 

If anyone else wants to work on it, please feel free to take over!

**Comment by gilest** [comment]
Hi there – I'm keen to try implementing this.

I'll be reading some code and experimenting with the current implementation to begin with.

/attempt #81

**Comment by ologbonowiwi** [comment]
putting myself in the queue 👋🏽

I will not actively work on it, and I do not have experience with Elixir, but the issue seems interesting.

**Comment by gilest** [comment]
Hi @zcesur I have staged the first half of this feature for review in #106
