### ISSUE TITLE
Chrome bug: Playing merged stream has a frozen frame segment

### ISSUE THREAD

**Issue by Lirianer** [algora-io/tv#93]
## Problem Description

When merging multiple video streams, using `Algora.Admin.merge_streams` added in #76, into a single stream, a playback glitch occurs when playing the resulting `.m3u8` in Chrome specifically after the `#EXT-X-DISCONTINUITY` tag.

The video freezes after the tag for the duration of the segment that follows, it then plays correctly.
Video evidence by @zcesur , the glitch occurs at 0:46. The frame freezes showing the first frame of the second segment after the discontinuity tag

https://github.com/user-attachments/assets/c6ac7829-4963-4c07-9b32-708410b84512

## Repro steps
- Run project
- Start streaming twice to create 2 different videos
- Execute `Algora.Admin.merge_streams/1` with the created videos
- Reproduce resulting video in Chrome

## Attempted solutions
- Experimented with adding and removing various tags in the `.m3u8` files, both Master Playlist and Playlist
  - Experimented with removing `#EXT-X-PROGRAM-DATE-TIME` tags.
  - Tried replacing datetime tags with daterange tags.
- Tried different values for existing tags.
- Attempted reversing the order of segments after the discontinuity tag.
- Tested with multiple video players including videojs and vidstack.
- Used Apple's mediastreamvalidator tool to identify potential issues in the playlist.

## Possible investigation
- Investigate if using MPEG-TS segments and/or separate A/V track
- When researching I've come across something mentioning keyframes at the start of the segments, I'm not very familiar with video formats but maybe something is missing or is redundant and causes the behaviour

**Comment by lastcanal** [comment]
This is no longer an issue with live streams created using the new pipeline architecture; see playback of a video created with `Admin.merge_streams/1` in chrome.

[Screencast from 2024-12-12 21-49-40.webm](https://github.com/user-attachments/assets/ba30bb16-cc14-42d6-b2e3-e46ac4bd6be6)
